// "201": "Eu nunca vi coisa mais bela que uma pessoa dessa roda."
// "202": "Eu nunca quis o coração de alguém."
// "203": "Eu nunca falsifiquei documentos."
// "204": "Eu nunca entrei de bico em uma festa."
// "205": "Eu nunca fiz xixi na calça."
// "206": "Eu nunca fiz xixi na piscina."
// "207": "Eu nunca fiz xixi na rua."
// "208": "Eu nunca fiz uma loucura por amor."
// "209": "Eu nunca sofri um acidente."
// "210": "Eu nunca tive uma experiência paranormal."
// "211": "Eu nunca menti jogando eu nunca."
// "212": "Eu nunca desisti de uma amizade."
// "213": "Eu nunca fui corno."
// "214": "Eu nunca chifrei."
// "215": "Eu nunca me arrependi do meu voto."
// "216": "Eu nunca coloquei a culpa em um amigo."
// "217": "Eu nunca levei uma multa."
// "218": "Eu nunca fingi que estava passando mal para não ir trabalhar."
// "219": "Eu nunca pedi dinheiro emprestado e fingi que esqueci."
// "220": "Eu nunca tomei remédio tarja preta."
// "221": "Eu nunca fui em um lugar de propósito para encontrar meu ex."
// "222": "Eu nunca grudei chiclete no cabelo de alguém."
// "223": "Eu nunca usei atestado médico falso."
// "224": "Eu nunca subornei."
// "225": "Eu nunca subestimei a capacidade de alguém."
// "226": "Eu nunca tive vontade de matar alguém."
// "227": "Eu nunca passei trote."
// "228": "Eu nunca dirigi bêbado."
// "229": "Eu nunca fingi que estava chorando."
// "230": "Eu nunca vomitei pelo nariz."
// "231": "Eu nunca pensei que estava sendo perseguido."
// "232": "Eu nunca caguei no mato."
// "233": "Eu nunca fiz questão de estar aqui."
// "234": "Eu nunca quebrei a cara."
// "235": "Eu nunca me apaixonei."
// "236": "Eu nunca tomei um porre porque estava na fossa."
// "237": "Eu nunca usei roupa com etiqueta para trocar depois."
// "238": "Eu nunca tive um relacionamento aberto."
// "239": "Eu nunca editei uma foto para parecer mais magro/gostoso."
// "240": "Eu nunca me humilhei por causa de alguém."
// "241": "Eu nunca tive que correr para salvar a minha vida."
// "242": "Eu nunca estive em um tiroteio."
// "243": "Eu nunca estive envolvido em uma catástrofe natural."
// "244": "Eu nunca pedi dinheiro na rua."
// "245": "Eu nunca estraguei a viagem de alguém."
// "246": "Eu nunca beijei alguém do mesmo sexo."
// "247": "Eu nunca fiz topless."
// "248": "Eu nunca tive vergonha de assumir meu voto publicamente."
// "249": "Eu nunca menti em uma entrevista de emprego."
// "250": "Eu nunca fiquei trancado para fora de casa."
// "251": "Eu nunca gritei no travesseiro."
// "252": "Eu nunca fui operado."
// "253": "Eu nunca chorei na escola."
// "254": "Eu nunca pensei que alguma coisa fosse mal assobrada."
// "255": "Eu nunca tomei um capote de bicicleta."
// "256": "Eu nunca sofri um acidente."
// "257": "Eu nunca jantei doces."
// "258": "Eu nunca fiz xixi na cama depois de criança."
// "259": "Eu nunca dei vexame."
// "260": "Eu nunca cheirei o chulé de alguém"
// "261": "Eu nunca deixei alguém cheirar meus dedos."
// "262": "Eu nunca comi escondido para não oferecer."
// "263": "Eu nunca escondi comida no meu quarto."
// "264": "Eu nunca menti para as autoridades."
// "265": "Eu nunca xinguei a mãe do juíiz."
// "266": "Eu nunca fumei cigarro."
// "267": "Eu nunca estacionei em vaga de idoso/deficientes."
// "268": "Eu nunca furei o sinal vermelho."
// "269": "Eu nunca quase atropelei alguém."
// "270": "Eu nunca pedi comida porque tinha preguiça de cozinhar."
// "271": "Eu nunca viajei sozinho."
// "272": "Eu nunca fui viciado em alguma coisa,"
// "273": "Eu nunca fiz terapia."
// "274": "Eu nunca misturei bebidas super fortes."
// "275": "Eu nunca me deparei com um inseto venenoso."
// "276": "Eu nunca escrevi uma carta de ódio."
// "277": "Eu nunca sugeri brincar de eu nunca apenas para descobrir os segredos de alguém."
// "278": "Eu nunca usei fraldas depois de adulto."
// "279": "Eu nunca fertilizei minhas plantas com algo incomum"
// "280": "Eu nunca tive um corte de cabelo ridículo."
// "281": "Eu nunca dei bafão na festa da firma."
// "282": "Eu nunca discuti no almoço de família."
// "283": "Eu nunca abandonei um grupo de WhatsApp."
// "284": "Eu nunca fui à Igreja."
// "285": "Eu nunca roubei alguma coisa do bar."
// "286": "Eu nunca fiz careta para crianças."
// "287": "Eu nunca copiei perguntas de eu nunca de outro site."
// "288": "Eu nunca roubei uma ideia."
// "289": "Eu nunca fui discriminado."
// "290": "Eu nunca fui machista."
// "291": "Eu nunca sofri machismo."
// "292": "Eu nunca fui demitido."
// "293": "Eu nunca demiti alguém."
// "294": "Eu nunca apostei dinheiro."
// "295": "Eu nunca vesti a camisa de outro time."
// "296": "Eu nunca mudei de religião."
// "297": "Eu nunca perdi um amigo por política."
// "298": "Eu nunca chorei de raiva por política."
// "299": "Eu nunca fui antiético."
// "300": "Eu nunca misturei remédios e álcool."
// "301": "Eu nunca tive diarreia e não conseguir chegar até o banheiro."
// "302": "Eu nunca fumei haxixe."
// "303": "Eu nunca usei documento falso."
// "304": "Eu nunca menti que eu era estudante para pagar meia entrada."
// "305": "Eu nunca caguei na balada."
// "306": "Eu nunca quis ficar com um amigo ou amiga."
// "307": "Eu nunca me arrumei antes da pessoa que estava dormindo comigo acordar e me ver bonito (a)."
// "308": "Eu nunca tive uma dívida."
// "309": "Eu nunca precisei pedir dinheiro emprestado."
// "310": "Eu nunca dei barraco."
// "311": "Eu nunca senti que alguém era muito bonito para mim."
// "312": "Eu nunca fiquei com mais do que 1 pessoa em 1 festa/noite."
// "313": "Eu nunca fui em uma micareta."
// "314": "Eu nunca quebrei alguma coisa e coloquei a culpa em outra pessoa."
// "315": "Eu nunca tomei tequila."
// "316": "Eu nunca dei um presente usado."
// "317": "Eu nunca assisti filme sem pagar."
// "318": "Eu nunca fiz faxina."
// "319": "Eu nunca tive uma alucinação."
// "320": "Eu nunca tomei Ayahuasca."
// "321": "Eu nunca comi cogumelos alucinógenos."
// "322": "Eu nunca fiz campanha política."
// "323": "Eu nunca me arrependi por ter votado em alguém."
// "324": "Eu nunca acordei sem saber onde estava."
// "325": "Eu nunca mudei de opinião só para agradar alguém."
// "326": "Eu nunca emprestei algo que não me devolveram."
// "327": "Eu nunca fiquei com uma pessoa de outro país."
// "328": "Eu nunca beijei um parente um amigo."
// "329": "Eu nunca fiz o mapa astral do crush."
// "330": "Eu nunca beijei alguém com bafo."
// "331": "Eu nunca fui assediado."
// "332": "Eu nunca cometi um grande erro na minha vida."
// "333": "Eu nunca estraguei um relacionamento."
// "334": "Eu nunca fui a um local proibidão."
// "335": "Eu nunca perdi um dente."
// "336": "Eu nunca copiei uma declaração de amor."
// "337": "Eu nunca fingi que estava gostando de uma comida e depois cuspi."
// "338": "Eu nunca me senti odiado."
// "339": "Eu nunca tive rancor de algo do passado."
// "340": "Eu nunca beijei na boca."
// "341": "Eu nunca joguei na loteria."
// "342": "Eu nunca namorei."
// "343": "Eu nunca menti para conseguir um trabalho."
// "344": "Eu nunca stalkeio as redes sociais de um ex."
// "345": "Eu nunca vivi um romance virtual."
// "346": "Eu nunca imaginei minha vida inteira ao lado de alguém impossível."
// "347": "Eu nunca menti que amava alguém."
// "348": "Eu nunca fiz um publi post."
// "349": "Eu nunca fiz coisas proibidas no local de trabalho."
// "350": "Eu nunca fui procurado pela polícia."
// "351": "Eu nunca apanhei."
// "352": "Eu nunca bebi até cair."
// "353": "Eu nunca brinquei de Eu Nunca com alguém da minha família."
// "354": "Eu nunca fiquei com alguém só porque a pessoa era boa de cama."
// "355": "Eu nunca deixei de falar com alguém por orgulho."
// "356": "Eu nunca menti para meu namorado."
// "357": "Eu nunca acreditei em notícias falsas."
// "358": "Eu nunca discuti por política."
// "359": "Eu nunca fiquei com alguém por interesse."
// "360": "Eu nunca me envolvi em uma polêmica."
// "361": "Eu nunca xinguei muito no Twitter."
// "362": "Eu nunca fiquei triste por não me sentir bonita."
// "363": "Eu nunca tive problemas de autoestima."
// "364": "Eu nunca paguei peitinho na praia."
// "365": "Eu nunca senti que não merecia um elogio."
// "366": "Eu nunca tive vergonha de ficar pelad@ na frente de alguém."
// "367": "Eu nunca não acreditei que alguém era afim de mim."
// "368": "Eu nunca continuei usando a conta do Netflix de um ex."
// "369": "Eu nunca recusei um presente."
// "370": "Eu nunca sofri preconceito."
// "371": "Eu nunca tive medo de sair na rua."
// "372": "Eu nunca tive uma amizade colorida."
// "373": "Eu nunca me escondi de alguém na rua."
// "374": "Eu nunca senti ciúmes de um amigo."
// "375": "Eu nunca depilei as partes íntimas."
// "376": "Eu nunca pedi perdão por algo que não me sentia culpado."
// "377": "Eu nunca algemei alguém."
// "378": "Eu nunca tive medo de um filme de terror."
// "379": "Eu nunca invejei o canal de um conhecido."
// "380": "Eu nunca comprei seguidores."
// "381": "Eu nunca dei like negativo em um vídeo da concorrência."
// "382": "Eu nunca pedi para amigos e familiares curtirem um post."
// "383": "Eu nunca curti minha própria foto."
// "384": "Eu nunca mandei mensagem errada."
// "385": "Eu nunca me apaixonei por alguém da internet."
// "386": "Eu nunca deletei uma publicação na rede social por não ter curtidas."
// "387": "Eu nunca pensei em participar do BBB."
// "388": "Eu nunca dei unfollow por recalque."
// "389": "Eu nunca mandei indireta nas redes sociais."
// "390": "Eu nunca me arrependi do meu nome de usuário."
// "391": "Eu nunca me arrependi de um post."
// "392": "Eu nunca postei fotos comprometedoras."
// "393": "Eu nunca expus outra pessoa nas redes sociais."
// "394": "Eu nunca copiei conteúdo de outra pessoa."
// "395": "Eu nunca fingi que tinha ganhado algo, mas na verdade comprei."
// "396": "Eu nunca fiquei com alguém famoso."
// "397": "Eu nunca usei Tinder ou app de paquera."
// "398": "Eu nunca fiquei com alguém do Tinder."
// "399": "Eu nunca tive um perfil falso."
// "400": "Eu nunca me apaixonei à primeira vista."
// "401": "Eu nunca fiz #publipost sem assumir que era."
// "402": "Eu nunca recebi algo por causa do meu canal/perfil."
// "403": "Eu nunca ri do canal de alguém."
// "404": "Eu nunca tomei um spoiler no Youtube."
// "405": "Eu nunca tive haters."
// "406": "Eu nunca tive um vídeo que foi um verdadeiro fracasso."
// "407": "Eu nunca fui copiado."
// "408": "Eu nunca pensei em excluir o meu canal."
// "409": "Eu nunca ganhei dinheiro com a internet."
// "410": "Eu nunca fiz um desafio ridículo só para ganhar visualizações."
// "411": "Eu nunca me arrependi por me expor demais."
// "412": "Eu nunca comecei a gostar de um canal que antes eu odiava."
// "413": "Eu nunca fiquei com alguém que conheci no YouTube."
// "414": "Eu nunca tive vergonha de postar alguma coisa."
// "415": "Eu nunca fiz vídeo com slime."
// "416": "Eu nunca fiz uma receita da internet que era péssima."
// "417": "Eu nunca gravei algo que era super complicado parecendo super fácil."
// "418": "Eu nunca recebi um alerta do YouTube."
// "419": "Eu nunca tive a minha conta invadida."
// "420": "Eu nunca deixei de aproveitar um momento importante porque estava pensando em fazer conteúdo."
// "421": "Eu nunca tive vergonha de fazer vídeo na frente de outras pessoa."
// "422": "Eu nunca pensei em largar tudo para viver de redes sociais."
// "423": "Eu nunca caí no gemidão do zap."
// "424": "Eu nunca virei um meme."
// "425": "Eu nunca fui hater."
// "426": "Eu nunca abandonei uma série."
// "427": "Eu nunca vi um filme mais do que 10 vezes."
// "428": "Eu nunca tive um passado comprometedor na internet."
// "429": "Eu nunca postei algo enquanto estava bêbado."
// "430": "Eu nunca escondi minhas redes sociais da minha família."
// "431": "Eu nunca tive medo de ser julgado (a)."
// "432": "Eu nunca segurei vela."
// "433": "Eu nunca fiz um amigo segurar vela."
// "434": "Eu nunca espero o microondas apitar antes de abrir."
// "435": "Eu nunca dancei em um pole dance."
// "436": "Eu nunca fingi que falava em outro idioma."
// "437": "Eu nunca fingi que não era comigo."
// "438": "Eu nunca fingi que eu era irmão de um amigo."
// "439": "Eu nunca comprei coisas falsificadas."
// "440": "Eu nunca gravei vídeo só de camiseta e calcinha/cueca sem ninguém perceber."
// "441": "Eu nunca usei maquiagem vencida."
// "442": "Eu nunca fiz um vídeo que, na verdade, era uma indireta para alguém."
// "443": "Eu nunca fiquei com seguidor ou fã."
// "444": "Eu nunca fui a um programa de auditório."
// "445": "Eu nunca dei uma entrevista,"
// "446": "Eu nunca participei de ouro canal."
// "447": "Eu nunca pensei em deletar o meu canal."
// "448": "Eu nunca esqueci alguém muito importante."
// "449": "Eu nunca fui rancoroso."
// "450": "Eu nunca fiz meu mapa astral."
// "451": "Eu nunca desisti de um crush por causa do signo dele."
// "452": "Eu nunca participei de um programa de rádio."
// "453": "Eu nunca fiz detox digital."
// "454": "Eu nunca meditei."
// "455": "Eu nunca usei aliança."
// "456": "Eu nunca brinquei de verdade ou desafio com perguntas quentes."
// "457": "Eu nunca apaguei meu histórico com medo de alguém ver."
// "458": "Eu nunca apaguei as sugestões do Instagram."
// "459": "Eu nunca briguei pelos comentários."
// "460": "Eu nunca fiquei com um seguidor."
// "461": "Eu nunca pedi para aparecer em um canal."
// "462": "Eu nunca desisto de um projeto."
// "463": "Eu nunca sofri censura."
// "464": "Eu nunca me arrependi de algo que publiquei."
// "465": "Eu nunca chorei lendo comentários."
// "466": "Eu nunca denunciei alguém na internet."
// "467": "Eu nunca gravei a TAG Eu Nunca."
// "468": "Eu nunca escondi minhas redes sociais dos meus pais."
// "469": "Eu nunca criei um perfil só para amigos."
// "470": "Eu nunca fui a uma exposição."
// "471": "Eu nunca chorei lendo um livro."
// "472": "Eu nunca enviei um cartão postal."
// "473": "Eu nunca discuti por WhatsApp."
// "474": "Eu nunca terminei um relacionamento por telefone."
// "475": "Eu nunca inventei uma TAG."
// "476": "Eu nunca faltei ao trabalho por beber demasiado na noite anterior."
// "477": "Eu nunca tive uma experiência paranormal."
// "478": "Eu nunca fiquei com um estranho."
// "479": "Eu nunca usei drogas."
// "480": "Eu nunca olhei o celular de alguém sem permissão."
// "481": "Eu nunca disse que prestava."
// "482": "Eu nunca traí você."
// "483": "Eu nunca olhei o armário do banheiro de um amigo."
// "484": "Eu nunca fiz ou recebi uma lap dance."
// "485": "Eu nunca enviei uma mensagem picante para a pessoa errada."
// "486": "Eu nunca fui algemado (por qualquer motivo)."
// "487": "Eu nunca cheirei minha roupa interior para saber se está limpa ou não."
// "488": "Eu nunca trabalhei alcoolizado."
// "489": "Eu nunca fiquei com um ex do meu melhor amigo."
// "490": "Eu nunca deletei um post em uma rede social por ter poucas curtidas."
// "491": "Eu nunca roubei um objeto de uma loja."
// "492": "Eu nunca engravidei."
// "493": "Eu nunca tive de correr para me salvar."
// "494": "Eu nunca quebrei algo em casa de amigo e não contei para ele."
// "495": "Eu nunca fiz fotos pelado."
// "496": "Eu nunca levei algo ilegal na fronteira."
// "497": "Eu nunca fui algemado."
// "498": "Eu nunca entrei em uma festa sem ser convidado."
// "499": "Eu nunca dei um tapa na cara."
// "500": "Eu nunca tomei um tapa na cara em público."
// "501": "Eu nunca saí na porrada."
// "502": "Eu nunca fiquei com alguém por interesse."
// "503": "Eu nunca achei que eu sou a pessoa mais bonita dessa roda."
// "504": "Eu nunca duvidei da minha sexualidade."
// "505": "Eu nunca vi alguém dançando e me excitei."
// "506": "Eu nunca fiquei beijando meu melhor amigo."
// "507": "Eu nunca fiquei preocupado pensando que teria um filho."
// "508": "Eu nunca fiz um procedimento estético e disse que era tudo natural."
// "509": "Eu nunca coloquei enchimento no sutiã / na calcinha."
// "510": "Eu nunca coloquei enchimento na sunga."
// "511": "Eu nunca viajei com drogas."
// "512": "Eu nunca tive uma bad trip."
// "513": "Eu nunca fiz simpatia para ter meu ex de volta / para conquistar alguém / para me vingar..."
// "514": "Eu nunca joguei água/comida em alguém."
// "515": "Eu nunca lambi uma ferida."
// "516": "Eu nunca provei leite materno depois de adulto."
// "517": "Eu nunca vi uma arma."
// "518": "Eu nunca fiz uma tatuagem ridícula."
// "519": "Eu nunca coloquei fogo em alguma coisa."
// "520": "Eu nunca disse 'te amo' sem querer"
// "521": "Eu nunca cheirei minhas roupas íntimas para saber se estavam sujas."
// "522": "Eu nunca tentei atrasar a menstruação."
// "523": "Eu nunca pensei que tivesse uma doença grave."
// "524": "Eu nunca escondi um segredo da minha família."
// "525": "Eu nunca fiz um teste de gravidez."
// "526": "Eu nunca fumei maconha."
// "527": "Eu nunca fiz uma declaração em público."
// "528": "Eu nunca descobri que um amigo estava sendo traído."
// "529": "Eu nunca desisti de uma amizade."
// "530": "Eu nunca enviei uma mensagem pesadona para o número errado."
// "531": "Eu nunca fui corrupto."
// "532": "Eu nunca tomei pílula do dia seguinte."
// "533": "Eu nunca fiz uma dieta louca."
// "534": "Eu nunca usei aliança."
// "535": "Eu nunca perdi um presente importante."
// "536": "Eu nunca usei pomada vaginal/peniana."
// "537": "Eu nunca desapareci da vida de alguém."
// "538": "Eu nunca fiquei excitado em um momento inadequado."
// "539": "Eu nunca me gravei fazendo aquilo."
// "540": "Eu nunca transei menstruada."
// "541": "Eu nunca tive vergonha dos meus próprios pensamentos."
// "542": "Eu nunca menti para meu chefe."
// "543": "Eu nunca fui corrupto."
// "544": "Eu nunca disse algo sem ter certeza do que estava falando."
// "545": "Eu nunca recebi flores sem saber de quem eram."
// "546": "Eu nunca fiquei preso dentro ou para fora de casa."
// "547": "Eu nunca soneguei impostos."
// "548": "Eu nunca convenci alguém a fazer algo errado,"
// "549": "Eu nunca coloquei a culpa em outra pessoa."
// "550": "Eu nunca assisti a vídeos proibidos."
// "551": "Eu nunca invadi a privacidade de alguém."
// "552": "Eu nunca acusei alguém injustamente."
// "553": "Eu nunca falei mal de um amigo."
// "554": "Eu nunca tomei um chá alucinógeno."
// "555": "Eu nunca fui testemunha de um crime."
// "556": "Eu nunca levei um bolo de um crush."
// "557": "Eu nunca me vinguei de algo."
// "558": "Eu nunca senti rancor."
// "559": "Eu nunca sofri bullying."
// "560": "Eu nunca pratiquei bullying."
// "561": "Eu nunca acreditei na internet ao invés de ir ao médico."
// "562": "Eu nunca quebrei uma promessa."
// "563": "Eu nunca fiz greve de fome."
// "564": "Eu nunca tive uma intoxicação alimentar,"
// "565": "Eu nunca fui a favor da legalização das armas."
// "566": "Eu nunca vendi meu voto."
// "567": "Eu nunca postei algo enquanto estava bêbado."
// "568": "Eu nunca vomitei dentro de um táxi."
// "569": "Eu nunca disfarcei uma marca de chupão."
// "570": "Eu nunca quis ficar com pai ou mãe de amigo."
// "571": "Eu nunca participei de uma suruba."
// "572": "Eu nunca fiquei com o pai/mãe de uma amiga/amigo."
// "573": "Eu nunca brochei com o cheiro dos genitais de alguém"
// "574": "Eu nunca perdi a camisinha dentro do meu corpo ou de outra pessoa."
// "575": "Eu nunca tive um squirt."
// "576": "Eu nunca tive a camisinha estourada."
// "577": "Eu nunca fiz uma lavagem anal."
// "578": "Eu nunca ouvi meu vizinho transando e comecei a transar também"
// "579": "Eu nunca fantasiei com meu chefe / com o namorado da minha melhor amiga / com o melhor amigo do meu namorado..."
// "580": "Eu nunca roubei calcinha/cueca de ex."
// "581": "Eu nunca fiquei com alguém para não me sentir só / ganhar algo / me vingar do meu ex..."
// "582": "Eu nunca gravei um vídeo pesadão."
// "583": "Eu nunca mandei umas fotos pesadonas."
// "584": "Eu nunca fiz sadomasoquismo."
// "585": "Eu nunca usei um vibrador."
// "586": "Eu nunca me masturbei com alguém do lado sem a pessoa saber."
// "587": "Eu nunca acordei sem saber o nome da pessoa que dormia ao meu lado."
// "588": "Eu nunca usei um objeto comum como brinquedo sexual."
// "589": "Eu nunca transei mais do que 5 vezes em uma noite."
// "590": "Eu nunca saí sem calcinha só para provocar alguém."
// "591": "Eu nunca tive dupla penetração."
// "592": "Eu nunca fiz troca de casais."
// "593": "Eu nunca transei no elevador."
// "594": "Eu nunca pratiquei pompoarismo."
// "595": "Eu nunca usei um gel anestésico para o sexo."
// "596": "Eu nunca fiz sexo de 4."
// "597": "Eu nunca fiz sexo à distância."
// "598": "Eu nunca medi um pênis."
// "599": "Eu nunca usei gelo na cama."
// "600": "Eu nunca me masturbei analmente."
// "601": "Eu nunca descobri o ponto G."
// "602": "Eu nunca olhei analisei vagina com um espelho."
// "603": "Eu nunca li contos eróticos."
// "604": "Eu nunca escrevi contos eróticos."
// "605": "Eu nunca transei no carro."
// "606": "Eu nunca fiz ou recebi um boquete."
// "607": "Eu nunca senti sabor de esperma ou fluído vaginal."
// "608": "Eu nunca fiz um 69."
// "609": "Eu nunca gozei na hora errada."
// "610": "Eu nunca dei um beijo grego."
// "611": "Eu nunca recebi um beijo grego."
// "612": "Eu nunca transei com a luz acesa."
// "613": "Eu nunca transei no chuveiro."
// "614": "Eu nunca tive um acidente sexual."
// "615": "Eu nunca transei no sofá."
// "616": "Eu nunca tive um sonho erótico."
// "617": "Eu nunca tive orgasmos múltiplos."
// "618": "Eu nunca usei camisinha de sabor."
// "619": "Eu nunca usei camisinha texturizada."
// "620": "Eu nunca me forcei a ficar com alguém só porque a pessoa era boa de cama."
// "621": "Eu nunca parei de ficar com alguém porque a pessoa beijava mal."
// "622": "Eu nunca tive vontade de ficar com alguém do mesmo sexo que eu."
// "623": "Eu nunca tive cãibra durante o sexo."
// "624": "Eu nunca quis ficar com alguém comprometido."
// "625": "Eu nunca usei lubrificante."
// "626": "Eu nunca precisei improvisar um lubrificante."
// "627": "Eu nunca joguei jogos eróticos."
// "628": "Eu nunca usei um vibrador caseiro."
// "629": "Eu nunca fiz sexo tântrico."
// "630": "Eu nunca usei um plug anal."
// "631": "Eu nunca usei um vibrador com arnês."
// "632": "Eu nunca usei uma boneca inflável."
// "633": "Eu nunca usei um estimulador de próstata."
// "634": "Eu nunca transei com alguém pensando em outra pessoa."
// "635": "Eu nunca transei dormindo."
// "636": "Eu nunca usei chocolate na cama."
// "637": "Eu nunca sujei a cama."
// "638": "Eu nunca criei uma playlist de músicas para transar."
// "639": "Eu nunca dancei em um pole dance."
// "640": "Eu nunca seduzi alguém."
// "641": "Eu nunca me exibi pela web cam."
// "642": "Eu nunca usei bolas chinesas."
// "643": "Eu nunca transei em uma festa."
// "644": "Eu nunca transei em uma banheira."
// "645": "Eu nunca transei na faculdade."
// "646": "Eu nunca mandei o mesmo nude para pessoas diferentes."
// "647": "Eu nunca menti sobre um sonho erótico."
// "648": "Eu nunca dei minhas roupas íntimas de presente para alguém."
// "649": "Eu nunca deixei alguém passar a mão em mim."
// "650": "Eu nunca fiz safadezas no cinema."
// "651": "Eu nunca li o kama sutra."
// "652": "Eu nunca usei gel anestésico para transar."
// "653": "Eu nunca gritei alto enquanto gozava."
// "654": "Eu nunca transei com alguém que tinha um piercing genital."
// "655": "Eu nunca disse 'eu te amo' no calor do momento."
// "656": "Eu nunca fui embora antes de a pessoa acordar."
// "657": "Eu nunca chupei os seios de alguém"
// "658": "Eu nunca ejaculei na hora errada."
// "659": "Eu nunca transei sentado."
// "660": "Eu nunca presenciei um pum vaginal."
// "661": "Eu nunca mordi a boca de alguém."
// "662": "Eu nunca paguei peitinho para ter bebida grátis."
// "663": "Eu nunca brochei."
// "664": "Eu nunca chamei o nome errado durante o sexo."
// "665": "Eu nunca fiquei com alguém da minha família."
// "666": "Eu nunca enviei uma mensagem quente para o número errado."
// "667": "Eu nunca tive sexo com alguém com o dobro da minha idade."
// "668": "Eu nunca pensei que podia ter uma DST."
// "669": "Eu nunca usei um objeto comum como brinquedo sexual e coloquei de volta."
// "670": "Eu nunca fiz sexo a 3."
// "671": "Eu nunca acho a ponta do durex na primeira vez."
// "672": "Eu nunca desejei ou fiquei com alguém do mesmo sexo."
// "673": "Eu nunca me masturbei ao ar livre."
// "674": "Eu nunca me exibi na webcam."
// "675": "Eu nunca fui infiel."
// "676": "Eu nunca fiz sexo na cama dos meus pais."
// "677": "Eu nunca transei na praia."
// "678": "Eu nunca tomei banho com outra pessoa."
// "679": "Eu nunca nadei pelado."
// "680": "Eu nunca fiquei com o ex de um(a) amigo(a)."
// "681": "Eu nunca fiquei com alguém dessa roda."
// "682": "Eu nunca fiz sexo anal."
// "683": "Eu nunca dei um beijo de Singapura."
// "684": "Eu nunca fiz sexo menstruada."
// "685": "Eu nunca fiz greve de sexo."
// "686": "Eu nunca fiz um strip tease."
// "687": "Eu nunca fingi um orgasmo."
// "688": "Eu nunca usei uma camisinha que brilha no escuro."
// "689": "Eu nunca me fantasiei de algo muito zoado para satisfazer alguém na cama."
// "690": "Eu nunca transei em uma suíte com espelho no teto."
// "691": "Eu nunca fui a um motel drive in."
// "692": "Eu nunca participei do surubão de Noronha."
// "693": "Eu nunca deixei marca de chupão em alguém."
// "694": "Eu nunca odiei um apelido carinhoso de alguém."
// "695": "Eu nunca desconfiei do meu parceiro."
// "696": "Eu nunca tive um namorado virtual."
// "697": "Eu nunca tive vergonha de revelar uma fantasia sexual."
// "698": "Eu nunca fiz sexo tântrico."
// "699": "Eu nunca imaginei meu/minha namorad@ com outra pesoa."
// "700": "Eu nunca imaginei nós dois fazendo uma coisa muito safada."
// "701": "Eu nunca usei alfo afrodisíaco."
// "702": "Eu nunca inventei uma desculpa esfarrapada para não transar."
// "703": "Eu nunca tive vontade de ir a uma casa de swing."
// "704": "Eu nunca usei vibrador enquanto estava com meu namorado."
// "705": "Eu nunca fiz algo constrangedor para agradar meu/minha parceiro."
// "706": "Eu nunca tive nojo de sêmen."
// "707": "Eu nunca tive nojo de menstruação."
// "708": "Eu nunca pensei que eu fosse viciad@ em sexo."
// "709": "Eu nunca usei um estimulador de clítoris."
// "710": "Eu nunca recebi um massagem erótica."
// "711": "Eu nunca usei máscaras na cama."
// "712": "Eu nunca testei uma posição sexual perigosa."
// "713": "Eu nunca pensei em outra pessoa enquanto me masturbava."
// "714": "Eu nunca tive vergonha de pedir alguma coisa na cama."
// "715": "Eu nunca pratiquei pompoarismo."
// "716": "Eu nunca pensei em fazer sexo anal."
// "717": "Eu nunca dominei uma pessoa na cama."
// "718": "Eu nunca fui dominad@ por alguém na cama."
// "719": "Eu nunca recebi uma massagem tailandesa."
// "720": "Eu nunca transei em quarto iluminado à luz de velas."
// "721": "Eu nunca falei sacanagem durante o sexo."
// "722": "Eu nunca fiz uma rapidinha."
// "723": "Eu nunca gozei de verdade."
// "724": "Eu nunca transei fora de casa."
// "725": "Eu nunca fiquei com alguém 10 anos mais velho do que eu."
// "726": "Eu nunca fiquei excitado com algum cheiro."
// "727": "Eu nunca tive vergonha da minha cara enquanto eu gozo."
// "728": "Eu nunca terminei com alguém porque a pessoa era ruim de cama."
// "729": "Eu nunca fiz sexo enquanto estava bebad@."
// "730": "Eu nunca fiz garganta profunda."
// "731": "Eu nunca transei na água."
// "732": "Eu nunca me excitei com a voz de alguém."
// "733": "Eu nunca senti dor enquanto transava."
// "734": "Eu nunca tentei apimentar a relação."
// "735": "Eu nunca entendi a diferença entre amor e paixão."
// "736": "Eu nunca fiz um anal giratório."
// "737": "Eu nunca recebi uma massagem yoni."
// "738": "Eu nunca usei lubrificante."
// "739": "Eu nunca tive um orgasmo mental."
// "740": "Eu nunca usei uma cadeira erótica."
// "741": "Eu nunca fiz um fio-terra."
// "742": "Eu nunca transei na frente de alguém."
// "743": "Eu nunca fui a uma praia nudista."
// "744": "Eu nunca me masturbei no chuveiro."
// "745": "Eu nunca provoquei uma pessoa."
// "746": "Eu nunca usei um vibrador líquido."
// "747": "Eu nunca fiz exerícios de Kegel."
// "748": "Eu nunca vesti algo só para seduzir alguém."
// "749": "Eu nunca estive na friend zone de alguém."
// "750": "Eu nunca fiz bondage."
// "751": "Eu nunca fiz sexo na balada."
// "752": "Eu nunca gozei só com 1 beijo."
// "753": "Eu nunca li contos eróticos."
// "754": "Eu nunca escrevi contos eróticos."
// "755": "Eu nunca dei um presente erótico."
// "756": "Eu nunca tentei controlar um orgasmo."
// "757": "Eu nunca dormi de conchinha."
// "758": "Eu nunca me considerei bom/boa de cama."
// "759": "Eu nunca encontrei meu ponto G."
// "760": "Eu nunca fiz fotos eróticas."
